version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - path: .env
        required: true
    volumes:
      - .:/app
  db:
    image: postgres:16
    env_file:
      - path: .env
        required: true
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5431:5431"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
